import { test } from 'node:test';
import assert from 'node:assert/strict';
import * as XLSX from 'xlsx';
import { calculateStats, productStatus, validateProducts, roundQuantity } from '../src/services/auditState.ts';
import { parseEleventaExcel } from '../src/services/eleventaParser.ts';
import { createAuditWorkbook } from '../src/services/eleventaExporter.ts';
import { terminalQr } from '../scripts/terminal-qr.mjs';
const product = overrides => ({ code: '001', description: 'Producto', cost: 10, price: 15, department: 'General', theoreticalStock: 5, physicalStock: 0, ...overrides });
const parse = rows => { const wb = XLSX.utils.book_new(); XLSX.utils.book_append_sheet(wb, XLSX.utils.aoa_to_sheet(rows), 'Productos'); return parseEleventaExcel(XLSX.write(wb, { type: 'array', bookType: 'xlsx' })); };
const header = ['Código', 'Descripción', 'Existencia', 'Costo', 'Precio Venta'];
test('pending zero is not a loss', () => { const p = product(); assert.equal(productStatus(p), 'not_counted'); assert.equal(calculateStats([p]).missingCostValue, 0); });
test('confirmed zero is a total loss', () => { const p = product({ counted: true }); const stats = calculateStats([p]); assert.equal(productStatus(p), 'missing'); assert.equal(stats.missingCostValue, 50); assert.equal(stats.auditedCount, 1); });
test('legacy counted stock migrates without losing progress', () => assert.equal(calculateStats([product({ physicalStock: 5 })]).matchCount, 1));
test('reset marker overrides legacy timestamp', () => assert.equal(productStatus(product({ counted: false, lastScannedAt: '2026-01-01' })), 'not_counted'));
test('decimal count does not create floating point discrepancy', () => assert.equal(productStatus(product({ theoreticalStock: .3, physicalStock: .1 + .2 })), 'match'));
test('unknown products are separated from catalog surplus', () => { const stats = calculateStats([product({ isUnregistered: true, physicalStock: 8 })]); assert.equal(stats.surplusCount, 0); assert.equal(stats.unregisteredCount, 1); });
test('stats include missing, surplus, exact and pending consistently', () => { const stats = calculateStats([product({ counted: true }), product({ physicalStock: 7 }), product({ physicalStock: 5 }), product()]); assert.equal(stats.auditedCount, 3); assert.equal(stats.notCountedCount, 1); assert.equal(stats.totalSurplusPieces, 2); assert.equal(stats.totalMissingPieces, 5); });
test('validator rejects malformed, duplicate and infinite saved data', () => { for (const input of [{}, null, [product(), product()], [product({ cost: Infinity })], [product({ physicalStock: -1 })], [product({ description: null })]]) assert.equal(validateProducts(input), false); });
test('validator accepts valid old records and explicit zero', () => assert.equal(validateProducts([product({ counted: true })]), true));
test('import preserves text barcode leading zeros', () => assert.equal(parse([header, ['001234', 'Arroz', 5, 10, 15]]).products[0].code, '001234'));
test('import preserves numeric barcode display formatting', () => { const ws = XLSX.utils.aoa_to_sheet([header, [123, 'Arroz', 5, 10, 15]]); ws.A2.z = '000000'; const wb = XLSX.utils.book_new(); XLSX.utils.book_append_sheet(wb, ws, 'Productos'); assert.equal(parseEleventaExcel(XLSX.write(wb, { type: 'array', bookType: 'xlsx' })).products[0].code, '000123'); });
test('duplicate import fails atomically', () => { const result = parse([header, ['001', 'A', 3], ['001', 'B', 9]]); assert.equal(result.products.length, 0); assert.match(result.errors[0], /duplicado/); });
test('invalid stock cannot silently turn into zero', () => assert.match(parse([header, ['001', 'A', 'muchos']]).errors[0], /número inválido/));
test('missing stock column is rejected', () => assert.equal(parse([['Código', 'Descripción'], ['001', 'A']]).products.length, 0));
test('cost and sale price columns remain distinct', () => { const result = parse([['Código', 'Descripción', 'Existencia', 'Precio costo', 'Precio venta'], ['001', 'A', 5, 10, 15]]); assert.equal(result.products[0].cost, 10); assert.equal(result.products[0].price, 15); });
test('MXN thousands and decimals are parsed', () => assert.equal(parse([header, ['001', 'A', '1,234.5', '$1,234.50', '1500']]).products[0].cost, 1234.5));
test('ambiguous decimal comma rejected rather than changed', () => assert.equal(parse([header, ['001', 'A', '1,25']]).products.length, 0));
test('missing code is not invented', () => assert.equal(parse([header, ['', 'A', 3]]).products.length, 0));
test('empty catalog is rejected', () => assert.equal(parse([header]).products.length, 0));
test('unsafe numeric barcode is rejected', () => assert.equal(parse([header, [Number.MAX_SAFE_INTEGER + 1, 'A', 3]]).products.length, 0));
test('export adjusts only counted registered products', () => { const products = [product({ counted: true }), product({ code: '002' }), product({ code: '003', physicalStock: 2, isUnregistered: true })]; const wb = createAuditWorkbook(products, calculateStats(products)); const rows = XLSX.utils.sheet_to_json(wb.Sheets[wb.SheetNames[0]]); assert.equal(rows.length, 1); assert.equal(rows[0]['Código'], '001'); assert.equal(rows[0]['Existencia'], 0); });
test('export pending differences are blank, not false losses', () => { const products = [product()]; const wb = createAuditWorkbook(products, calculateStats(products)); const rows = XLSX.utils.sheet_to_json(wb.Sheets[wb.SheetNames[1]], { defval: null }); assert.equal(rows[0]['Diferencia (Piezas)'], null); assert.equal(rows[0]['Estado'], 'SIN CONTAR'); });
test('export keeps workbook sheets and adjustment column names', () => { const wb = createAuditWorkbook([], calculateStats([])); assert.deepEqual(wb.SheetNames, ['Ajuste_Inventario_eleventa', 'Auditoría_Discrepancias', 'Resumen_Ejecutivo']); assert.deepEqual(XLSX.utils.sheet_to_json(wb.Sheets[wb.SheetNames[0]], { header: 1 })[0], header.slice(0,2).concat(['Existencia','Costo','Precio Venta','Departamento','Tipo'])); });
test('QR includes quiet zone and bounds input length', () => { assert.equal(terminalQr('http://192.168.1.1:5173').split('\n').length, 33); assert.throws(() => terminalQr('x'.repeat(33))); });
test('rounding keeps six decimals', () => assert.equal(roundQuantity(1.23456789), 1.234568));
